public_html/protected/controllers/PlacesController.php
<?php
class PlacesController extends RestController
{
    public function actionIndex()
    {
        if(Yii::app()->user->checkAccess('viewPlaces')) {
            $this->render('index');
        } else {
            $this->redirect(array('site/login'));
        }
    }

    public function actionList()
    {
        if(!Yii::app()->user->checkAccess('viewPlaces')) {
            $this->_sendResponse(403);
            return;
        }
        $places = Places::model()->findAll();
        echo CJSON::encode($places);
    }

    public function actionView($id)
    {

    }

    public function actionCreate()
    {
        if(!Yii::app()->user->checkAccess('addPlace')) {
            $this->_sendResponse(403);
            return;
        }
        $data = CJSON::decode(file_get_contents('php://input'));

        $place = new Places();
        $place->attributes = $data;
        if($place->save()) {
            $this->_sendResponse(200, CJSON::encode($place));
        } else {
            $this->_sendResponse(500, CJSON::encode(array(
                'message' => 'Could not save Place',
                'errors' => $place->getErrors()
            )));
        }
    }

    public function actionUpdate($id)
    {
        $data = CJSON::decode(file_get_contents('php://input'));
        $place = Places::model()->findByPk($id);
        if (!Yii::app()->user->checkAccess('updatePlace', array('place'=>$place))) {
            $this->_sendResponse(403);
            return;
        }
        if(null === $place){
            $this->_sendResponse(404, CJSON::encode(array('message'=>'Could not find place with id = '.$id)));
        }
        $place->attributes = $data;
        if($place->save()) {
            $this->_sendResponse(200, CJSON::encode($place));
            return;
        } else {
            $this->_sendResponse(500, CJSON::encode(array(
                'message' => 'Could not save Place',
                'errors' => $place->getErrors()
            )));
        }
    }

    public function actionDelete($id)
    {
        $place = Places::model()->findByPk($id);
        if (null === $place) {
            $this->_sendResponse(404, CJSON::encode(array('message'=>'Could not find place with id = '.$id)));
            return;
        }
        if (!Yii::app()->user->checkAccess('deletePlace', array('place'=>$place))) {
            $this->_sendResponse(403);
            return;
        }
        if ($place->delete()) {
            $this->_sendResponse(200, CJSON::encode($place));
        } else {
            $this->_sendResponse(500, CJSON::encode(array(
                'message'=>'Could not delete place',
                'errors'=>$place->getErrors(),
            )));
        }
    }
}

public_html/protected/controllers/UsersController.php
<?php

class UsersController extends Controller
{
    public $layout = '//layouts/yiistrap.col2';

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        if (Yii::app()->user->checkAccess('viewUser')) {
            $this->render('view', array(
                'model' => $this->loadModel($id),
            ));
        }
        else {
            throw new CHttpException(403);
        }
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        if (!Yii::app()->user->checkAccess('addUser')) {
            throw new CHttpException(403);
        }

        $model = new Users;

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

        if (isset($_POST['Users'])) {
            $model->attributes = $_POST['Users'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        if (!Yii::app()->user->checkAccess('updateUser')) {
            throw new CHttpException(403);
        }

        $model = $this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

        if (isset($_POST['Users'])) {
            $model->attributes = $_POST['Users'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        if (!Yii::app()->user->checkAccess('deleteUser')) {
            throw new CHttpException(403);
        }

        if (Yii::app()->request->isPostRequest) {
// we only allow deletion via POST request
            $this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        } else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        if (!Yii::app()->user->checkAccess('viewUsers')) {
            throw new CHttpException(403);
        }

        $dataProvider = new CActiveDataProvider('Users');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        if (!Yii::app()->user->checkAccess('viewUsers')) {
            throw new CHttpException(403);
        }

        $model = new Users('search');
        $model->unsetAttributes(); // clear any default values
        if (isset($_GET['Users']))
            $model->attributes = $_GET['Users'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Users the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = Users::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Users $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'users-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

public_html/protected/views/layouts/yiistrap.col2.php
<?php $this->beginContent('//layouts/yiistrap'); ?>
    <div class="row-fluid">

        <div class="span9">
            <?php echo $content; ?>
        </div>

        <div class="span3">
            <div class="well">
            <?php
            $this->widget('zii.widgets.CMenu', array(
                'items'=>$this->menu,
                'htmlOptions'=>array('class'=>'nav nav-list'),
                'firstItemCssClass'=>'nav-header',
                'activeCssClass'=>'active',
            ));
            ?>
            </div>
        </div>
    </div>
<?php $this->endContent(); ?>

public_html/protected/views/layouts/yiistrap.php
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    <meta name="description" content="<?php echo CHtml::encode($this->pageTitle); ?>">
    <meta name="viewport" content="width=device-width">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link href="favicon.ico" rel="icon" type="image/x-icon" />

    <?php Yii::app()->bootstrap->register(); ?>

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/app.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/jquery.fancybox.css" />
    <base href="<?php echo Yii::app()->createAbsoluteUrl('/'); ?>/">
</head>
<body>
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <span class="brand"><?php echo CHtml::encode(Yii::app()->name); ?></span>
            <?php $this->widget('zii.widgets.CMenu',array(
                'items'=>array(
                    array('label'=>Yii::t('app', 'PLACES'), 'url'=>array('/places/index'), 'visible'=>!Yii::app()->user->isGuest),
                    array('label'=>Yii::t('app', 'USERS'), 'url'=>array('/users/index'), 'visible'=>Yii::app()->user->checkAccess('viewUsers')),
                    array('label'=>Yii::t('app', 'ABOUT'), 'url'=>array('/site/page', 'view'=>'about')),
                    array('label'=>Yii::t('app', 'CONTACT'), 'url'=>array('/site/contact')),
                    array('label'=>Yii::t('app', 'LOGIN'), 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
                    array('label'=>Yii::t('app', 'LOGOUT').' ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
                ),
                'activeCssClass'=>'active',
                'htmlOptions'=>array(
                    'class'=>'nav',
                ),
            )); ?>
        </div>
    </div>
</header>
<div class="container">
    <?php echo $content; ?>
</div>

<footer class="navbar-fixed-bottom">
    <div class="container">
        <p class="text-center">&copy; <a href="http://www.simplecoding.org">SimpleCoding.org</a> <?php echo date('Y'); ?></p>
    </div>
</footer>
<?php
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/jquery.fancybox.js', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/jquery.mousewheel-3.0.6.pack.js', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/main.js', CClientScript::POS_END);
?>
</body>
</html>